# 3. 대입 연산과 변수

## 대입 연산

- 값의 보관(오른쪽에서 왼쪽으로)
- 좌측: 이름
- 우측: 값, 식, 함수 호출 등..

## 변수(Variables)
- 값을 기억해 두고 필요할 때 활용할 수 있음
- 중간 계산값을 저장하거나 누적 등

- = (대입 연산자)를 이용하여 값, 또는 연산 결과를 저장한다.
- 값(객체)을 저장하는 메모리 상의 공간을 가리키는(object reference: 객체 참조) 이름
- 파이썬에서는 선언 및 할당이 동시에 이루어짐

### Naming rule
- 소문자와 대문자는 서로 다르게 취급
- 변수의 이름은 문자와 숫자, 밑줄(_)로 이루어짐
- 변수의 이름 중간에 공백이 들어가면 안됨.
- 숫자로 시작할 수 없음
- 키워드는 사용할 수 없음
- 의미 있는 이름을 사용(권장)

In [7]:
a = 10
b = 'hi'
a = b
c = 3.14

In [3]:
# 예약어
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 '__peg_parser__',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [5]:
spam = 15

"""
- 변수에 값을 저장하면 메모리에 저장하게 되는데, 메모리
- 주소값을 확인하려면 id() 함수를 사용
- 시스템 RAM에 4351621872 주소에 spam=15 값을 넣어놨다.
"""
id(spam)

4351621872

In [8]:
%whos

Variable   Type      Data/Info
------------------------------
a          str       hi
b          str       hi
c          float     3.14
keyword    module    <module 'keyword' from '/<...>ib/python3.9/keyword.py'>
spam       int       15


In [9]:
del a

In [10]:
%whos

Variable   Type      Data/Info
------------------------------
b          str       hi
c          float     3.14
keyword    module    <module 'keyword' from '/<...>ib/python3.9/keyword.py'>
spam       int       15


# 4. List
- 여러 개의 데이터를 하나의 변수에 저장하고자 할 때 매우 유용함
- 리스트는 [  ]로 묶어주고, 리스트의 아이템은 ,(컴마)로 구분함
- 리스트의 아이템에 접근하고자 할 때에는 인덱스를 사용함
- 인덱스는 0부터 시작함!!

In [12]:
shape = ['turple', 'arrow', 'circle', 'square']
shape[1]

'arrow'

In [13]:
[1, 2, 3, 4] + ['a', 'b', 'c', 'd']

[1, 2, 3, 4, 'a', 'b', 'c', 'd']

In [14]:
shape * 3

['turple',
 'arrow',
 'circle',
 'square',
 'turple',
 'arrow',
 'circle',
 'square',
 'turple',
 'arrow',
 'circle',
 'square']

## 리스트 슬라이싱

- 리스트의 일부를 정한 규칙으로 추출
- 끝은 인덱스의 범위를 넘어가도 됨

리스트명[시작 : 끝 : 스텝]
- 시작 <= ... <= 끝 - 1

In [15]:
a = [1,2,3,4,5,6,7,8,9,10]

In [16]:
type(a)

list

In [17]:
a[1:11:2]

[2, 4, 6, 8, 10]

# 5. range()

- 범위
- range(끝)
- range(시작, 끝)
- range(시작, 끝, 스텝)

In [18]:
range(10)

range(0, 10)

In [19]:
list( range(10) )

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
for x in range(10):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [21]:
len( range(10) )

10

In [ ]:
# 이미지를 불러올 때, 배치 단위로 불러오는 이유

# 6. tuple

- 소괄호로 묶은 순서가 있는 자료의 모음

In [22]:
a = (1, 2, 3, 4, 5)

In [23]:
%whos

Variable   Type      Data/Info
------------------------------
a          tuple     n=5
add_list   list      n=8
b          str       hi
c          float     3.14
keyword    module    <module 'keyword' from '/<...>ib/python3.9/keyword.py'>
shape      list      n=4
spam       int       15
x          int       9


In [24]:
type(a)

tuple

In [25]:
a[0] = 0

TypeError: 'tuple' object does not support item assignment

In [31]:
# 원소가 한 개인 튜플 (값 5)
b = (5,)

print(type(b))
print(b)

<class 'tuple'>
(5,)


### 튜플 자료의 슬라이싱

In [32]:
b = tuple( range(10) )
b

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [33]:
b[ : -1]

(0, 1, 2, 3, 4, 5, 6, 7, 8)

### 다양한 tuple 값 대입

In [38]:
x = 1,
print(x)
print(type(x))

y = 1,2
print(y)
print(type(y))

(1,)
<class 'tuple'>
(1, 2)
<class 'tuple'>


In [39]:
c, d = 1, 2
print(c)
print(d)

1
2


# 7. 딕셔너리
- 사전식 자료 관리
- key와 value 쌍으로 이루어진 자료구조
- 딕셔너리는 중괄호{ }로 묶여 있음
- key를 인덱스로 사용

In [1]:
phone_book={'신사임당': '010-1234-5678', '홍길동': '010-4532-4532'}

In [2]:
phone_book.keys()

dict_keys(['신사임당', '홍길동'])

In [4]:
phone_book.values()

dict_values(['010-1234-5678', '010-4532-4532'])

In [5]:
phone_book.items()

dict_items([('신사임당', '010-1234-5678'), ('홍길동', '010-4532-4532')])

In [6]:
del phone_book['신사임당']

In [7]:
phone_book

{'홍길동': '010-4532-4532'}

# 8. 넘파이 ndarray

## NumPy
- 파이썬 라이브러리
- 행렬이나 대규모 다차원 배열을 쉽게 처리
- 배열에는 모두 동일한 자료형만 저장
- 메모리에 연속적으로 저장

In [9]:
import numpy as np

## 8.1 배열의 생성
- numpy.array()
- ndim: 배열의 차원 반환
- shape: 배열의 형태 반환
- type() : 배열 자료형 반환

In [10]:
ar1 = np.array([10.3,80.2,15.5,30, 95, 65, 70, 40, 50])   # 1차원 배열

In [14]:
ar1 = np.array([10.3, 80.2, 15.5, 30, 95, 65, 70, 40, 50],
               dtype=np.float16)
ar1

array([10.3, 80.2, 15.5, 30. , 95. , 65. , 70. , 40. , 50. ],
      dtype=float16)

In [15]:
type( ar1 )

numpy.ndarray

In [16]:
ar1.ndim

1

In [19]:
ar1.shape

(9,)

In [20]:
%whos

Variable     Type       Data/Info
---------------------------------
ar1          ndarray    9: 9 elems, type `float16`, 18 bytes
ar2          ndarray    3x6: 18 elems, type `int64`, 144 bytes
ar3          ndarray    2x2x3: 12 elems, type `int64`, 96 bytes
np           module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
phone_book   dict       n=1


In [22]:
a = ar1.astype(int)
print(a)

[10 80 15 30 95 65 70 40 50]


In [24]:
# 벡터화 연산
b = np.ones_like( ar1 )
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [25]:
# broadcasting
a + b

array([11., 81., 16., 31., 96., 66., 71., 41., 51.])

In [26]:
a + 20

array([ 30, 100,  35,  50, 115,  85,  90,  60,  70])

In [27]:
ar2 = np.array([[ 30, 40,  50,  60,  70,   80],
                [110, 120, 130, 140, 150, 160],
                [210, 215, 220, 225, 230, 235]])
ar2

array([[ 30,  40,  50,  60,  70,  80],
       [110, 120, 130, 140, 150, 160],
       [210, 215, 220, 225, 230, 235]])

In [28]:
ar2.ndim, ar2.shape

(2, (3, 6))

In [29]:
ar3 = np.array([
                [[100,20,30], [40,150,60]],

                [[70,80,190], [100,100,100]]
               ])
ar3

array([[[100,  20,  30],
        [ 40, 150,  60]],

       [[ 70,  80, 190],
        [100, 100, 100]]])

In [35]:
ar3[0], ar3[0].ndim, ar3.ndim

(array([[100,  20,  30],
        [ 40, 150,  60]]),
 2,
 3)

In [36]:
ar3.shape # 차원, 행, 열

(2, 2, 3)

In [34]:
ar3.size # 2*2*3 (원소의 수)

12

In [37]:
np.array( range(1, 11) )

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
np.arange( 1, 11 )

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
ar = np.arange(1, 11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
ar.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [42]:
ar2

array([[ 30,  40,  50,  60,  70,  80],
       [110, 120, 130, 140, 150, 160],
       [210, 215, 220, 225, 230, 235]])

In [43]:
ar2[ :2 , 2:5 ] # [ 행 슬라이싱, 열 슬라이싱 ]

array([[ 50,  60,  70],
       [130, 140, 150]])

In [45]:
ar2[ [0,  2] , : ] # [ 행 선택, 열 선택 ]

array([[ 30,  40,  50,  60,  70,  80],
       [210, 215, 220, 225, 230, 235]])

In [48]:
ar2[ : , [1, 3] ] # [ 행 선택, 열 선택 ]

array([[ 40,  60],
       [120, 140],
       [215, 225]])

In [49]:
ar2[ :, -1] # => Pandas -> deep learning

array([ 80, 160, 235])

In [50]:
ar2[ :, [-1]] # => Pandas -> deep learning

array([[ 80],
       [160],
       [235]])

# 9. Pandas

In [3]:
import pandas as pd

## 9.1 Sereis

In [6]:
dic = {'철수': 84, '영이':21, '길동':87, '미영': 100, '순이':59, '철이':46}
s = pd.Series(dic)
s

철수     84
영이     21
길동     87
미영    100
순이     59
철이     46
dtype: int64

In [8]:
s.index

Index(['철수', '영이', '길동', '미영', '순이', '철이'], dtype='object')

In [9]:
s.values

array([ 84,  21,  87, 100,  59,  46])

In [11]:
names1 = ['철수', '영이', '길동', '미영', '순이', '철이']
score1 = [84, 21, 87, 100, 59, 46]
s1 = pd.Series( score1, index=names1 )
s1

철수     84
영이     21
길동     87
미영    100
순이     59
철이     46
dtype: int64

In [12]:
s1.ndim

1

In [13]:
s1.shape

(6,)

In [15]:
len(s1)

6

In [16]:
s1[2:5]

길동     87
미영    100
순이     59
dtype: int64

In [17]:
s1['길동':'순이']

길동     87
미영    100
순이     59
dtype: int64

## DataFrame

In [20]:
scores = [[84, 87, 78], [21, 15, 84], [87, 84, 76],
          [100, 87, 99], [59, 99, 59], [46, 77, 56]]
lectures =  ['국어','영어', '수학']
d = pd.DataFrame(scores, index=names1, columns=lectures)
d

국어  영어  수학
철수   84  87  78
영이   21  15  84
길동   87  84  76
미영  100  87  99
순이   59  99  59
철이   46  77  56

In [22]:
d.index

Index(['철수', '영이', '길동', '미영', '순이', '철이'], dtype='object')

In [23]:
d.columns

Index(['국어', '영어', '수학'], dtype='object')

In [24]:
d.values

array([[ 84,  87,  78],
       [ 21,  15,  84],
       [ 87,  84,  76],
       [100,  87,  99],
       [ 59,  99,  59],
       [ 46,  77,  56]])

In [21]:
e = pd.DataFrame(scores, columns=lectures)
e

국어  영어  수학
0   84  87  78
1   21  15  84
2   87  84  76
3  100  87  99
4   59  99  59
5   46  77  56

In [25]:
scoresWithLectures = {'국어': [84, 21, 87,100, 59, 46],
                      '영어': [87, 15, 84, 87, 99, 77],
                      '수학': [78, 84, 76, 99, 59, 56]}
d = pd.DataFrame(scoresWithLectures, index=names1)
d

국어  영어  수학
철수   84  87  78
영이   21  15  84
길동   87  84  76
미영  100  87  99
순이   59  99  59
철이   46  77  56

In [29]:
d['국어']

철수     84
영이     21
길동     87
미영    100
순이     59
철이     46
Name: 국어, dtype: int64

In [36]:
d['국어']['철수':'길동']

철수    84
영이    21
길동    87
Name: 국어, dtype: int64

In [50]:
d.loc[ '철수':'길동', '국어' ]

철수    84
영이    21
길동    87
Name: 국어, dtype: int64

In [48]:
d.loc[ '철수':'길동', ['국어'] ]

국어
철수  84
영이  21
길동  87

In [51]:
d.loc[ '철수':'길동', '국어':'영어' ]

국어  영어
철수  84  87
영이  21  15
길동  87  84

In [46]:
d.iloc[0:3, 0]

철수    84
영이    21
길동    87
Name: 국어, dtype: int64

In [42]:
d.iloc[0:3, [0]]

국어
철수  84
영이  21
길동  87