<a href="https://colab.research.google.com/github/godud2604/AI-bootcamp/blob/main/RNN_%EB%AC%B8%EC%9E%A5%EC%83%9D%EC%84%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# RNN 활용 문장 생성

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [2]:
corpus = '''안경을 쓰고 있으면 상대방의 말이 번역돼 렌즈에 표시된다.
 AR 안경을 사용해 북경어에서 영어로 또는 그 반대로 영어에서 스페인어로 번역한다.
청각 장애인이나 난청이 있는 사람들에게 읽을 수 있는 텍스트를 제공한다.
보청기 없이도 의사 소통할 수 있는 방법을 보여주었다.
가상현실기술은 가상환경에 사용자를 몰입하게 하여 실제환경을 볼 수 없다.
'''

In [8]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts( [corpus] )
vocab_size = len( tokenizer.word_index ) + 1
print('단어 집합의 크기 : %d' % vocab_size)
print(tokenizer.word_index)

단어 집합의 크기 : 42
{'있는': 1, '수': 2, '안경을': 3, '쓰고': 4, '있으면': 5, '상대방의': 6, '말이': 7, '번역돼': 8, '렌즈에': 9, '표시된다': 10, 'ar': 11, '사용해': 12, '북경어에서': 13, '영어로': 14, '또는': 15, '그': 16, '반대로': 17, '영어에서': 18, '스페인어로': 19, '번역한다': 20, '청각': 21, '장애인이나': 22, '난청이': 23, '사람들에게': 24, '읽을': 25, '텍스트를': 26, '제공한다': 27, '보청기': 28, '없이도': 29, '의사': 30, '소통할': 31, '방법을': 32, '보여주었다': 33, '가상현실기술은': 34, '가상환경에': 35, '사용자를': 36, '몰입하게': 37, '하여': 38, '실제환경을': 39, '볼': 40, '없다': 41}


In [12]:
import nltk
nltk.download('punkt')

sequences = list()
for line in  nltk.sent_tokenize(corpus): # 각 문장들의 리스트
    print('line', line)
    encoded = tokenizer.texts_to_sequences( [ line ] )[0] # text를 숫자로 변경
    print('encoded', encoded)
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

print('학습에 사용할 샘플의 개수: %d' % len(sequences))

line 안경을 쓰고 있으면 상대방의 말이 번역돼 렌즈에 표시된다.
encoded [3, 4, 5, 6, 7, 8, 9, 10]
line AR 안경을 사용해 북경어에서 영어로 또는 그 반대로 영어에서 스페인어로 번역한다.
encoded [11, 3, 12, 13, 14, 15, 16, 17, 18, 19, 20]
line 청각 장애인이나 난청이 있는 사람들에게 읽을 수 있는 텍스트를 제공한다.
encoded [21, 22, 23, 1, 24, 25, 2, 1, 26, 27]
line 보청기 없이도 의사 소통할 수 있는 방법을 보여주었다.
encoded [28, 29, 30, 31, 2, 1, 32, 33]
line 가상현실기술은 가상환경에 사용자를 몰입하게 하여 실제환경을 볼 수 없다.
encoded [34, 35, 36, 37, 38, 39, 40, 2, 41]
학습에 사용할 샘플의 개수: 41


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [13]:
sequences

[[3, 4],
 [3, 4, 5],
 [3, 4, 5, 6],
 [3, 4, 5, 6, 7],
 [3, 4, 5, 6, 7, 8],
 [3, 4, 5, 6, 7, 8, 9],
 [3, 4, 5, 6, 7, 8, 9, 10],
 [11, 3],
 [11, 3, 12],
 [11, 3, 12, 13],
 [11, 3, 12, 13, 14],
 [11, 3, 12, 13, 14, 15],
 [11, 3, 12, 13, 14, 15, 16],
 [11, 3, 12, 13, 14, 15, 16, 17],
 [11, 3, 12, 13, 14, 15, 16, 17, 18],
 [11, 3, 12, 13, 14, 15, 16, 17, 18, 19],
 [11, 3, 12, 13, 14, 15, 16, 17, 18, 19, 20],
 [21, 22],
 [21, 22, 23],
 [21, 22, 23, 1],
 [21, 22, 23, 1, 24],
 [21, 22, 23, 1, 24, 25],
 [21, 22, 23, 1, 24, 25, 2],
 [21, 22, 23, 1, 24, 25, 2, 1],
 [21, 22, 23, 1, 24, 25, 2, 1, 26],
 [21, 22, 23, 1, 24, 25, 2, 1, 26, 27],
 [28, 29],
 [28, 29, 30],
 [28, 29, 30, 31],
 [28, 29, 30, 31, 2],
 [28, 29, 30, 31, 2, 1],
 [28, 29, 30, 31, 2, 1, 32],
 [28, 29, 30, 31, 2, 1, 32, 33],
 [34, 35],
 [34, 35, 36],
 [34, 35, 36, 37],
 [34, 35, 36, 37, 38],
 [34, 35, 36, 37, 38, 39],
 [34, 35, 36, 37, 38, 39, 40],
 [34, 35, 36, 37, 38, 39, 40, 2],
 [34, 35, 36, 37, 38, 39, 40, 2, 41]]

In [15]:
sample_len_list = [ len(l) for l in sequences]
print( sample_len_list )
max_len = max(sample_len_list)   # 모든 샘플에서 길이가 가장 긴 샘플의 길이 출력
print('샘플의 최대 길이 : {}'.format(max_len))

[2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8, 9]
샘플의 최대 길이 : 11


In [16]:
# 일정 길이로 맞추기 위해 padding 적용
sequences = pad_sequences( sequences, maxlen = max_len)
print(sequences)

[[ 0  0  0  0  0  0  0  0  0  3  4]
 [ 0  0  0  0  0  0  0  0  3  4  5]
 [ 0  0  0  0  0  0  0  3  4  5  6]
 [ 0  0  0  0  0  0  3  4  5  6  7]
 [ 0  0  0  0  0  3  4  5  6  7  8]
 [ 0  0  0  0  3  4  5  6  7  8  9]
 [ 0  0  0  3  4  5  6  7  8  9 10]
 [ 0  0  0  0  0  0  0  0  0 11  3]
 [ 0  0  0  0  0  0  0  0 11  3 12]
 [ 0  0  0  0  0  0  0 11  3 12 13]
 [ 0  0  0  0  0  0 11  3 12 13 14]
 [ 0  0  0  0  0 11  3 12 13 14 15]
 [ 0  0  0  0 11  3 12 13 14 15 16]
 [ 0  0  0 11  3 12 13 14 15 16 17]
 [ 0  0 11  3 12 13 14 15 16 17 18]
 [ 0 11  3 12 13 14 15 16 17 18 19]
 [11  3 12 13 14 15 16 17 18 19 20]
 [ 0  0  0  0  0  0  0  0  0 21 22]
 [ 0  0  0  0  0  0  0  0 21 22 23]
 [ 0  0  0  0  0  0  0 21 22 23  1]
 [ 0  0  0  0  0  0 21 22 23  1 24]
 [ 0  0  0  0  0 21 22 23  1 24 25]
 [ 0  0  0  0 21 22 23  1 24 25  2]
 [ 0  0  0 21 22 23  1 24 25  2  1]
 [ 0  0 21 22 23  1 24 25  2  1 26]
 [ 0 21 22 23  1 24 25  2  1 26 27]
 [ 0  0  0  0  0  0  0  0  0 28 29]
 [ 0  0  0  0  0  0  0  0 28

In [19]:
sequences = np.array(sequences)
X = sequences[:, :-1]
y = sequences[:, -1]

In [20]:
print(X)

[[ 0  0  0  0  0  0  0  0  0  3]
 [ 0  0  0  0  0  0  0  0  3  4]
 [ 0  0  0  0  0  0  0  3  4  5]
 [ 0  0  0  0  0  0  3  4  5  6]
 [ 0  0  0  0  0  3  4  5  6  7]
 [ 0  0  0  0  3  4  5  6  7  8]
 [ 0  0  0  3  4  5  6  7  8  9]
 [ 0  0  0  0  0  0  0  0  0 11]
 [ 0  0  0  0  0  0  0  0 11  3]
 [ 0  0  0  0  0  0  0 11  3 12]
 [ 0  0  0  0  0  0 11  3 12 13]
 [ 0  0  0  0  0 11  3 12 13 14]
 [ 0  0  0  0 11  3 12 13 14 15]
 [ 0  0  0 11  3 12 13 14 15 16]
 [ 0  0 11  3 12 13 14 15 16 17]
 [ 0 11  3 12 13 14 15 16 17 18]
 [11  3 12 13 14 15 16 17 18 19]
 [ 0  0  0  0  0  0  0  0  0 21]
 [ 0  0  0  0  0  0  0  0 21 22]
 [ 0  0  0  0  0  0  0 21 22 23]
 [ 0  0  0  0  0  0 21 22 23  1]
 [ 0  0  0  0  0 21 22 23  1 24]
 [ 0  0  0  0 21 22 23  1 24 25]
 [ 0  0  0 21 22 23  1 24 25  2]
 [ 0  0 21 22 23  1 24 25  2  1]
 [ 0 21 22 23  1 24 25  2  1 26]
 [ 0  0  0  0  0  0  0  0  0 28]
 [ 0  0  0  0  0  0  0  0 28 29]
 [ 0  0  0  0  0  0  0 28 29 30]
 [ 0  0  0  0  0  0 28 29 30 31]
 [ 0  0  0

In [21]:
print(y)

[ 4  5  6  7  8  9 10  3 12 13 14 15 16 17 18 19 20 22 23  1 24 25  2  1
 26 27 29 30 31  2  1 32 33 35 36 37 38 39 40  2 41]


In [22]:
# 원핫인코딩
y = to_categorical(y, num_classes=vocab_size)
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [34]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

embedding_dim = 10
hidden_units = 16

model = Sequential()
model.add( Embedding( vocab_size, embedding_dim ) )
model.add( SimpleRNN( hidden_units ) )
model.add( Dense( vocab_size, activation='softmax' ) )
model.compile(loss= 'categorical_crossentropy' , optimizer= 'adam',
              metrics=['accuracy'])
model.fit(X, y, epochs=500, verbose=0)
print(model.evaluate(X, y))

2/2 [==============================] - 0s 10ms/step - loss: 0.2306 - accuracy: 1.0000
[0.2306271493434906, 1.0]


In [35]:
import time
def sentence_generation(model, tokenizer, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word
    sentence = ''
    print(init_word, end=" ")

    # n번 반복
    for _ in range(n):
        # 현재 단어에 대한 정수 인코딩과 패딩
        encoded = tokenizer.texts_to_sequences([ current_word])[0]
        encoded = pad_sequences( [encoded], maxlen = max_len )
        # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        result = model.predict( encoded, verbose=0 )
        result = np.argmax(result, axis=1)[0]
        print(result)

        for word, index in tokenizer.word_index.items() :
            # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면 break
            if index == result:
                break

        # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        current_word = current_word + ' '  + word

        # 예측 단어를 문장에 저장
        sentence = sentence + ' ' + word
        time.sleep(0.5)
        print(word, end=" ")

    sentence = init_word + sentence
    return sentence

In [36]:
print(sentence_generation(model, tokenizer, '안경을', 7))

안경을 4
쓰고 5
있으면 6
상대방의 7
말이 8
번역돼 9
렌즈에 10
표시된다 안경을 쓰고 있으면 상대방의 말이 번역돼 렌즈에 표시된다


In [37]:
print(sentence_generation(model, tokenizer, 'AR', 10))

AR 3
안경을 12
사용해 13
북경어에서 14
영어로 15
또는 16
그 17
반대로 18
영어에서 19
스페인어로 20
번역한다 AR 안경을 사용해 북경어에서 영어로 또는 그 반대로 영어에서 스페인어로 번역한다


In [38]:
print(sentence_generation(model, tokenizer, '청각', 7))

청각 22
장애인이나 23
난청이 1
있는 24
사람들에게 25
읽을 2
수 1
있는 청각 장애인이나 난청이 있는 사람들에게 읽을 수 있는
